In [2]:
import numpy as np
import math
import sys
sys.path.append("..")
import logistic_regression

from code_misc.utils import MyUtils

In [8]:
LR = logistic_regression.LogisticRegression()
X_test1 = np.array([[1,2],[3,4],[5,6]])
y_test1 = np.array([[-1.0],[1.0],[1.0]])
X_test1 = np.insert(X_test1, 0, 1, axis=0)

In [9]:
print("testing _sigmoid: ")
# for s in X_test1:
#     print(logistic_regression.LogisticRegression._sigmoid(s))

print("\n\ntesting _v_sigmoid: ")
print(logistic_regression.LogisticRegression._v_sigmoid(X_test1))

testing _sigmoid: 


testing _v_sigmoid: 
[[0.73105858 0.73105858]
 [0.73105858 0.88079708]
 [0.95257413 0.98201379]
 [0.99330715 0.99752738]]


In [10]:
print(X_test1.ndim)

LR.fit(X_test1,y_test1,1,0.001,100,False,degree=3)

print(LR.predict(X_test1))

2


ValueError: operands could not be broadcast together with shapes (5,1) (4,1) 

In [6]:
d = 7
w = np.array([[0],]*(d))
w



array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [7]:
w = np.insert(w, 0, 1, axis=1)
w

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

In [9]:
pred = np.array([[ 0.02089376],
 [ 0.00692787],
 [ 0.01841312],
 [ 0.00350539],
 [ 0.00770415],
 [ 0.01954956],
 [-0.00406338],
 [ 0.01722698],
 [ 0.00311387],
 [-0.00169806]])
np.sign(pred)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.]])