In [1]:
import numpy as np
import math_util as mu

In [7]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([.01, .5, 100, 0, -1])

In [8]:
print(mu.MyMath.tanh(x1))
print(mu.MyMath.tanh(x2))

[0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ]
[ 0.00999967  0.46211716  1.          0.         -0.76159416]


In [15]:
tx = np.tanh(1)
print(f"{1 - (tx * tx)} == {mu.MyMath.tanh_de(1)}")
tx = np.tanh(x1)
print(f"\n{1 - (tx * tx)}\n==\n{ mu.MyMath.tanh_de(x1)}")
tx = np.tanh(x2)
print(f"\n{1 - (tx * tx)}\n==\n{ mu.MyMath.tanh_de(x2)}")


0.41997434161402614 == 0.41997434161402614

[4.19974342e-01 7.06508249e-02 9.86603717e-03 1.34095068e-03
 1.81583231e-04]
==
[4.19974342e-01 7.06508249e-02 9.86603717e-03 1.34095068e-03
 1.81583231e-04]

[0.99990001 0.78644773 0.         1.         0.41997434]
==
[0.99990001 0.78644773 0.         1.         0.41997434]


In [17]:
tx = ((np.tanh(2 / 2) + 1) / 2)
print(f"{tx} == {mu.MyMath.logis(2)}")
txd = (mu.MyMath.tanh_de(2 / 0.5)) / 4
print(mu.MyMath.logis_de(2))
print(f"{txd} == {mu.MyMath.logis_de(2)}")

0.8807970779778824 == 0.8807970779778824
0.0003352376707564664
0.0003352376707564664 == 0.0003352376707564664


In [19]:
print(mu.MyMath.iden(25))
print(mu.MyMath.iden_de(25))

print(mu.MyMath.iden(x1))
print(mu.MyMath.iden_de(x1))

25
1.0
[1 2 3 4 5]
[1. 1. 1. 1. 1.]


In [20]:
x3 = np.array([-3, -2, -1, 0, 1, 2, 3])
for x in x3:
    print(f"relu({x}) = {mu.MyMath.relu(x)} and relu'({x}) = {mu.MyMath.relu_de(x)}")

relu(-3) = 0 and relu'(-3) = 0
relu(-2) = 0 and relu'(-2) = 0
relu(-1) = 0 and relu'(-1) = 0
relu(0) = 0 and relu'(0) = 0
relu(1) = 1 and relu'(1) = 1
relu(2) = 2 and relu'(2) = 1
relu(3) = 3 and relu'(3) = 1


In [22]:
print(mu.MyMath.relu_de(-3) == mu.MyMath._relu_de_scaler(-3))

True
